version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
