version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - '8080:8080'
